apply plugin: 'kotlin'


dependencies {
    implementation "net.dankito.utils:java-utils:$javaUtilsVersion"

    implementation "org.jsoup:jsoup:$jsoupVersion"

    testImplementation ("junit:junit:$junitVersion", {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    })
    testImplementation "org.hamcrest:hamcrest-library:$hamcrestVersion"
}
