apply plugin: 'kotlin'


dependencies {
    implementation project(':SyncManager')
    implementation project(':CouchbaseLiteEntityManagerBase')
    implementation project(':DataServices')

    implementation "com.couchbase.lite:couchbase-lite-java-listener:$couchbaseLiteVersion"


    testImplementation ("junit:junit:$junitVersion", {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    })
    testImplementation "org.hamcrest:hamcrest-library:$hamcrestVersion"

    testImplementation "org.mockito:mockito-core:$mockitoVersion"

    testImplementation "com.nhaarman:mockito-kotlin-kt1.1:$mockitoKotlinVersion" // so that Mockito.any() doesn't return null which null-safe Kotlin parameter don't like
    // for how to enable mocking final class (which is standard in Kotlin) with Mockito see https://github.com/mockito/mockito/wiki/What's-new-in-Mockito-2#mock-the-unmockable-opt-in-mocking-of-final-classesmethods

    testImplementation project(':JavaCouchbaseLiteEntityManager')

    testImplementation "ch.qos.logback:logback-core:$logbackVersion"
    testImplementation "ch.qos.logback:logback-classic:$logbackVersion"
}
