apply plugin: 'kotlin'


dependencies {
    api project(':NewsReader')

    testImplementation ("junit:junit:$junitVersion", {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    })
    testImplementation "org.hamcrest:hamcrest-library:$hamcrestVersion"
}


test {
    ignoreFailures = true
}
