apply plugin: 'kotlin'


dependencies {
    api project(':DataModel')

    api "net.dankito.utils:java-utils:$javaUtilsVersion"

    api "org.jsoup:jsoup:$jsoupVersion"


    implementation "com.github.axet:wget:$wgetVersion", {
        exclude group: 'com.thoughtworks.xstream', module: 'xstream'
    }


    testImplementation "junit:junit:$junitVersion"
    testImplementation "org.assertj:assertj-core:$assertJVersion"

}
