apply plugin: 'kotlin'


dependencies {
    api project(':Utils')

    implementation "net.dankito.readability4j:readability4j:1.0.3", {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib'
    }

    testImplementation ("junit:junit:$junitVersion", {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    })
    testImplementation "org.hamcrest:hamcrest-library:$hamcrestVersion"
    testImplementation "org.assertj:assertj-core:$assertJVersion"
}


test {
    ignoreFailures = true
}
