package net.dankito.deepthought.model


enum class NetworkSetting {

    MESSAGES_PORT,
    BASIC_DATA_SYNCHRONIZATION_PORT,
    SYNCHRONIZATION_PORT,
    ADDED_DISCOVERED_DEVICE,
    REMOVED_DISCOVERED_DEVICE,
    ADDED_CONNECTED_DEVICE_PERMITTED_TO_SYNCHRONIZE,
    REMOVED_CONNECTED_DEVICE_PERMITTED_TO_SYNCHRONIZE,
    ADDED_DEVICES_ASKED_FOR_PERMITTING_SYNCHRONIZATION,
    REMOVED_DEVICES_ASKED_FOR_PERMITTING_SYNCHRONIZATION,
    ADDED_UNKNOWN_DEVICE_NOTIFICATION_SHOWN_TO_USER,
    REMOVED_UNKNOWN_DEVICE_NOTIFICATION_SHOWN_TO_USER

}
